language: node_js
node_js:
  - "10"

script:
  - npm run start-production

deploy:
  provider: pages
  skip-cleanup: true

  github-token: $token # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: ./dist
  on:
    condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+
    branch: master
