language: node_js
node_js:
  - "10"

cache:
  directories:
    - node_modules

before_install:
  - chmod +x travis.sh

script:
  - ./travis.sh
  # - npm test
  # - npm run start-production

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $token # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: ./dist
  on:
    condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+
